# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wAE55VBIzss6GYrwxOBaiiyomBRfaMaE
"""

import pandas as pd
import numpy as np

c=pd.read_csv("/content/college_1.csv")
d=pd.read_csv("/content/college_2.csv")

c.head()

d.head()

#merge those two csv files (after getting as dataframes, get them as a single dataframe)
df = pd.concat([c,d],ignore_index=True)

# as Exceeded expectations.csv
exceeded_expectation = df[df["CodeKata Score"]>15000]
exceeded_expectation.to_csv("exceeded expectation.csv")
exceeded_expectation

# if codekate score < 7000 (Unsatisfactory.csv)
Unsatisfactory = df[df["CodeKata Score"]<7000]
Unsatisfactory.to_csv("Unsatisfactory.csv")
Unsatisfactory

#Average of previous week geekions vs this week geekions (i.e Previous Geekions vs CodeKata Score)
import matplotlib.pyplot as plt
avg1 = df["Previous Geekions"].sum()/len(df["Name"])
avg2 = df["CodeKata Score"].sum()/len(df["Name"])

plt.bar("Previous Geekions",avg1,width=0.5)
plt.bar("CodeKata Score",avg2,width=0.5)
plt.show()

#No of students participated
no_students =len(df["Name"])
print(no_students)

#Average completion of python course or my_sql or python english or computational thinking

average_complt = df['python']/len(df['python'])
print(average_complt)
print(df.agg({'python':'mean'}))

# rising star of the week (top 3 candidate who performed well in that particular week)

df.nlargest(3, 'Rising')

# Shining stars of the week (top 3 candidates who has highest geekions)"""

df.nlargest(3, 'Previous Geekions')

#Department wise codekata performence (pie chart)

import plotly.express as px
fig=px.pie(df,names='Department',values='CodeKata Score',title='Department wise codekata performence')
fig.update_traces(textinfo='percent',textposition='outside')

# Department wise toppers (horizantal bar graph or any visual representations of your choice)"""

CSE = df[df["Department"]=="Computer Science and Engineering"]
# CSE.to_csv("CSE.csv")
CSE
max_cse = CSE["CodeKata Score"].max()
max_cse

ECE = df[df["Department"]=="Electronics and Communication Engineering"]
ECE
max_ece = ECE["CodeKata Score"].max()
max_ece

EEE = df[df["Department"]=="Electronics and Electrical Engineering"]
EEE
max_eee = ECE["CodeKata Score"].max()
max_eee

import plotly.express as px

x2 = ["CSE","ECE","EEE"]
y2 = [max_cse,max_ece,max_eee]
fig = px.bar(x=x2, y = y2)
fig.show()